### ISSUE TITLE
Creating new topics

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#2430]
@anisa-hawes noted an issue: in the [editorial guidelines](https://programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file) there's a mention of editing the lessonfilter.js file:

`Edit /js/lessonfilter.js so the filter button to filter the lesson page to that topic works. Search the file for the ten-line chunk of code beginning with $('#filter-api'), copy and paste that chunk of code, and replace the two appearances of “api” with your new topic.`

But it doesn't appear that the filter-api code is in that file—I'm wondering if it was taken out when we revamped the search functionality. Do we still need to include this step?

**Comment by jenniferisasi** [comment]
Per my perusal through multiple files and on #2429, I arrived at this conclusion: 

`Inspecting the lessonfilter.js file, I believe you might be correct (though I am no expert on JS, more like super novice 😅). I understand that if you add a new topic to the lesson and then to /_data/topics.yml it should show on the button options (until you add it to _data I think it will ignore said topic in the lesson metadata).`

**Comment by anisa-hawes** [comment]
Thank you, @svmelton and @jenniferisasi.

To confirm, if editors want to add a new topic, they need to update `/_data/topics.yml` following this format:

```
- type: website
  displayname:
    en: "Digital Publishing"
    es: "Publicación digital"
    fr: "Publication numérique"
    pt: "Publicação digital"
  description:
    en: "How to design and develop a website such as a digital exhibit or research blog."
    es: "Iníciate en el diseño y desarrollo de exposiciones o blogs de investigación."
    fr: "Concevoir et développer un site web pour une exposition numérique ou un blog de recherche."
    pt: "Como projetar e desenvolver um site, como uma exibição digital ou um blogue de pesquisa."
```

I'll add this to our re-draft of the EN guidelines.
