### ISSUE TITLE
Onboarding tasks: new editors joining our English team

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2481]
I am updating our Authors (ph_authors.yml) _ Avatars (avatars) file because a group of new editors are joining our English team.

**Comment by anisa-hawes** [comment]
Please edit the following as necessary. Follow this format:

```
- name: Firstname Surname
  team: true
  team_start: 2022
  institution: Your Institution
  github: githubhandle
  email: address@email.com
  twitter: twitterhandle
  url: "https://website.com/"
  sortname: Surname
  orcid: 0000-0001-0002-0003
  affiliation:
    en: |
      Your Institution, UK
    es: |
      Your Institution, Reino Unido
    fr: |
      Your Institution, Royaume-Uni
    pt: |
      Your Institution, Reino Unido
  bio:
    en: |
      Your bio in English.
    es: |
      Your bio en español.
    fr: |
      Your bio en français.
    pt: |
      Your bio em português.
  team_roles:
    - english
    - editorial
  status: volunteer
```
