### ISSUE TITLE
Add new topics 'modeling' and 'metadata'

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3435]
I will add the new topics 'modeling' and 'metadata' to our list of lesson topics.

This will also require a short description of what this topic refers to, with translations in French, Spanish and Portuguese, in this format:

```
- type: topic
  displayname:
    en: "modeling"
    es: "modelado"
    fr: "[...]"
    pt: "[...]"
  description:
    en: "Lessons which [...]"
    es: "Lecciones que [...]"
    fr: "[...]"
    pt: "[...]"
```

**Comment by anisa-hawes** [comment]
Olá @ericbrasiln, Bonjour @marie-flesch,

May I ask if you could check if the following descriptions of two new topics 'modeling' and 'metadata' make good sense in your context?

I am merging in PR #3440 (without closing this Issue) because we are preparing to publish one EN and one ES lesson which we'd like to label with the new topics. Jenn and Alex have confirmed that they are happy with the descriptions but we would be happy make an adjustment if you'd like to suggest a change.

We can also add these topics to past lessons, so please let us know if you can think of any past lessons which could usefully be labelled within these categories?

I also want to clarify that the new topic filter buttons will not display until there is at least one lesson within your journal labelled with that new topic.  

```
- type: modeling
  displayname:
    en: "modeling"
    es: "modelización"
    fr: "modélisation"
    pt: "modelagem"
  description:
    en: "Using formal, computational, or data-driven techniques to simulate, analyze, and predict complex systems."
    es: "Utilizar técnicas formales, informáticas, o basadas en datos para simular, analizar y predecir sistemas complejos."
    fr: "Utiliser des techniques formelles, informatiques, ou basées sur des données pour simuler, analiser et prédire des systèmes complexes."
    pt: "Utilizar técnicas formais, computacionais ou baseadas em dados para simular, analisar e prever sistemas complexos."
```

```
- type: metadata
  displayname:
    en: "metadata"
    es: "metadata"
    fr: "métadonnées"
    pt: "metadados"
  description:
    en: "Learn how to create, interpret, or manage 'data about data'."
    es: "Aprender a crear, interpretar o administrar 'datos sobre datos'."
    fr: "Apprendre à créer, interpréter ou gérer des 'données à propos de données'."
    pt: "Aprender a criar, interpretar ou gerir 'dados sobre dados'."
```
