### ISSUE TITLE
best way to filter/store deprecated lessons

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#462]
current index page uses 

```
{% assign alllessons = (site.pages | where: "lesson" , "true") %}
```

to find lessons. this also finds deprecated lessons stored in the deprecated folder in the lessons directory. it is tricky to filter on the deprecated flag because it's not set for non-deprecated lessons.
this relies on this code from _config.yml
```
  -
    scope:
      path: "lessons"
    values:
      lesson: true
```
for the time being, to ignore the  deprecated lesson, i have added to the preview site:
```
  -
    scope:
      path: "lessons/deprecated"
    values:
      lesson: false
```
any thoughts on the best way to do this?
1) we can store deprecated lessons somewhere other than the lessons directory
2) we can add a deprecated flag to each lesson, even if most are false (so that we can filter it on the lesson index page)
3) solution above
4) something i'm not thinking of.
